### ISSUE TITLE
Ingredient load seems broken.

### ISSUE THREAD

**Issue by keenanmcnamara12** [keenanmcnamara12/WhatsForDinnerMVC#25]
It seems like all ingredients are loaded for each each recipe.  Basically 17,000+ ingredients per recipe seems wrong (and I think that's what's happening).

**Comment by keenanmcnamara12** [comment]
Existing:
![image](https://user-images.githubusercontent.com/29746018/28757726-e1373c76-754e-11e7-8165-c8f9bbe79448.png)

Fixed:
![image](https://user-images.githubusercontent.com/29746018/28757820-dce2c076-7550-11e7-8be7-05be86d8503b.png)
Notice - we're getting a subquery out of this one, so that'll probably look good for grading since it's a bit more complicated.

With the above fix, we don't load thousands of things into the modal :) 
![image](https://user-images.githubusercontent.com/29746018/28757819-d37a8442-7550-11e7-8028-118138c9619d.png)

**Comment by keenanmcnamara12** [comment]
Don't worry, I realized the styling was gross in the previous post.  Now it looks better.
![image](https://user-images.githubusercontent.com/29746018/28757945-55f28738-7553-11e7-9425-55d1d18bdaab.png)

I think the null checking that I'm using to determine if the "-" should display slows the modal down.  Or maybe it was just a coincidence of testing - let me know if the popup seems slow to you too.

**Comment by skrepsky** [comment]
Add the filter. I didn't make a subquery though because that's not necessary (we already have recipe id from ingredient).
