### ISSUE TITLE
Delete a menu from the menu list page

### ISSUE THREAD

**Issue by keenanmcnamara12** [keenanmcnamara12/WhatsForDinnerMVC#7]
Want a button to do this on the menu list page.

Undecided if we want to add a button to the menu edit page.

**Comment by keenanmcnamara12** [comment]
Implemented delete, but the stored procedure spDeleteMenu needs to have the order that the menu is deleted from the tables flipped or we get a FK exception thrown.  

Here's what the working sp should look like.  I left the original location of the delete in as commented lines.

![image](https://user-images.githubusercontent.com/29746018/28757679-ed5acd0c-754d-11e7-99cb-240121864753.png)

**Comment by skrepsky** [comment]
Fixed.
